application: matrobotwebsite
version: 2
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.3"

builtins:
- django_wsgi: on
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: matrobot/templates/media/favicon.ico
  upload: matrobot/templates/media/favicon\.ico

- url: /robots\.txt
  static_files: matrobot/templates/media/robots.txt
  upload: matrobot/templates/media/robots\.txt

- url: /media
  static_dir: matrobot/templates/media
  